
services:
  backend:
    build: .
    container_name: nest-backend
    ports:
      - "3001:3001"   # ánh xạ cổng 3001 thay vì 3000
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:6
    container_name: nest-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
